### ISSUE TITLE
How to convert boxShadow; need ability to use string overload in these cases

### ISSUE THREAD

**Issue by davedawkins** [alfonsogarciacaro/Feliz.Engine#4]
I can't see an API that will let me express this in Feliz.Engine. There's an `int` API, but this case has float+units
```
        Css.boxShadow "-0.4rem 0.01rem 0.3rem rgba(0,0,0,.5)"
```

This is another example of needing a string interface that allows me to continue without trying to navigate the type system :)

**Comment by alfonsogarciacaro** [comment]
Yes, I had a similar issue with Css.transition :) I'm ok with adding string overloads to avoid having ti fight the type system 👍

**Comment by alfonsogarciacaro** [comment]
I added the overload to accept "raw" string values. As commented above, I'm ok with adding overloads to accept strings in complex properties in case the typed ones don't cover all the cases, so please feel free to edit the file directly when you need one of them.

On the other hand, I'm realizing there are too many overloads in the Feliz Css API. Sometimes there are not necessary, like lists vs arrays (instead of just accepting seq) or an extra overload instead of an optional argument, but there seems to be also an insistence on accepting an int or float wherever a CssUnit is expected, even when the method accepts multiple values which makes overload grow exponentially.

Ints and floats are converted to px but it's not immediately obvious and sometimes Feliz was just relying on React doing this (I guess) as seen in #8. Maybe we can leave the overloads using ints for single-parameter methods for conveniences, but I would remove them for floats or methods with multiple parameters, one can just use `length` in those cases (and now static classes can also be opened with `open type length`). I've already [started some cleanup](https://github.com/alfonsogarciacaro/Feliz.Engine/commit/0e20b803473c871b00d1ecf3379bf5c8cd875b42), I need to get it finished before a stable release because then removing any overload is a breaking change 😅
